---
# tasks file for container-base
- name: update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update-cache: yes
- name: install some useful pacakges
  become: yes
  apt:
    pkg: 
      - p7zip-full
      - unzip
      - curl
- name: install pip
  become: yes
  apt:
    name: python3-pip
- name: install ansible dependency pip docker
  pip:
    name: 
      - docker
      - docker-compose
- name: install fail2ban
  become: yes
  apt:
    name: fail2ban