---
# tasks file for container-base
- name: update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update-cache: yes
- name: install some useful packages
  become: yes
  apt:
    pkg: 
      - p7zip-full
      - unzip
      - curl
- name: install pip
  become: yes
  apt:
    name: python3-pip
- name: install ansible dependency pip docker
  pip:
    name: 
      - docker
      - docker-compose
- name: install fail2ban
  become: yes
  apt:
    name: fail2ban
- name: remove ssh host keys in container
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/ssh/ssh_host_*"
- name: reconfigure ssh server
  shell: dpkg-reconfigure openssh-server