---
# tasks file for roles/user
- name: add my user
  become: yes
  ansible.builtin.user:
    name: liam
    password: "{{ my_user_pass }}"
- name: add to sudo group
  become: yes
  ansible.builtin.user:
    name: liam
    groups: sudo
    append: yes
- name: sudo without password (NOPASSWD)
  become: yes
  blockinfile:
    path: /etc/sudoers
    backup: yes
    block: |
      liam    ALL=(ALL) NOPASSWD: ALL
    validate: visudo -c %s
