version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    command: postgres -c 'max_connections=400'
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
