version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    env_file:
      - .env
    volumes:
      - ${BOOKSTACK_DATA}:/config
    ports:
      - 6875:80
    restart: unless-stopped
