---
# tasks file for roles/deploy_watchtower

- name: creating required directories
  file:
    path: "/home/{{ ansible_user }}/docker/watchtower/"
    state: directory

- name: copy compose file
  copy:
    src: files/{{ item }}
    dest: /home/{{ ansible_user }}/docker/watchtower/{{ item }}
  loop:
    - docker-compose.yaml

- name: copy env file
  template:
    src: env.j2
    dest: /home/{{ ansible_user }}/docker/watchtower/.env
  notify: restart watchtower container

- name: run watchtower container
  community.docker.docker_compose:
    project_src: '/home/{{ ansible_user }}/docker/watchtower'
    files:
      - docker-compose.yaml
  register: output

- ansible.builtin.debug:
    var: output