all:
  vars:
    # These are global variables, they can be overwritten at the host level
    ansible_user: liam
    # We can use variables by putting them in double curly brackets
    # these variables are assigned in a vault file and read here
    #ansible_ssh_pass: '{{ host_default_pass }}'
    # The "become_pass" is used from sudo commands
    ansible_become_pass: '{{ host_default_pass }}'
    ansible_ssh_private_key_file: '{{ host_ssh_key }}'
    ansible_python_interpreter: auto_silent
    # This little trick is to use short hostnames like myhost
    # instead of myhost.mynetwork.local, the domain can be overwritten
    # at the host level as well
    #ansible_host: '{{ inventory_hostname }}.{{ host_domain }}'
    #host_domain: 'mynetwork.local'
  hosts:
    # These are hosts on the global level, we can also group hosts as
    # seen below under "children"
  children:
    # These are host groups, we can use groups later to target
    # hosts as a group instead of individually
    # hosts without ips defiend re configured in .ssh/config
    containers:
      vars:
        ansible_user: root
      hosts:
        pihole:
          ansible_host: 192.168.1.124
        mysql-server:
          ansible_host: 192.168.1.245
    virtual_machines:
      hosts:
        media-server:
        docker:
    oci:
      vars:
        ansible_user: ubuntu
      hosts:
        lorenz:
